pipeline:
  build:
    image: g3rv4/transifex-builder
    commands:
      - "git clone git@github.com:g3rv4-docker/transifex.git output-image"
      - "npm install"
      - "npm run build"
      - "rm -rf output-image/app/frontend"
      - "mkdir -p output-image/app/frontend"
      - "cp -r dist/* output-image/app/frontend/"
      - "cd output-image"
      - "git add app/frontend"
      - "git commit -m 'Frontend update: ${DRONE_COMMIT_SHA}'"
      - "git push"